# Generated by Django 4.0.3 on 2022-03-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts', '0004_alter_forumpost_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
