# Generated by Django 4.0.3 on 2022-03-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_posts', '0005_alter_forumpost_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
